# Generated by Django 3.1.3 on 2021-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0002_auto_20210122_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tagline',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
