# Generated by Django 3.1.3 on 2021-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0003_auto_20210122_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title_url',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default='Unspecified video', max_length=100),
        ),
    ]
