# Generated by Django 3.1.3 on 2021-01-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0006_auto_20210123_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
