# Generated by Django 3.1.3 on 2021-01-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0007_video_video_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(max_length=100),
        ),
    ]
