# Generated by Django 3.1.3 on 2021-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0008_auto_20210123_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
