# Generated by Django 3.1.3 on 2021-01-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0010_customercourse_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
