# Generated by Django 3.1.3 on 2021-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0011_auto_20210127_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
