# Generated by Django 3.1.3 on 2021-01-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0012_auto_20210127_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercourse',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
